spring.application.name=helpdesk-backend
spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk
spring.datasource.username=root
spring.datasource.password=Tanmay@dbms09

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
